import type { InventoryAlert, Product } from "../types/inventory";

export const products: Product[] = [
    {
        id: '1',
        barcode: '5901234123457',
        name: 'Organic Whole Milk',
        description: 'Fresh organic milk from local farms',
        quantity: 24,
        lowStockThreshold: 10,
        expiryDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // 5 days
        expiryWarningDays: 7,
        category: 'Dairy',
        location: 'Cooler A',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '2',
        barcode: '4006381333931',
        name: 'Arabica Coffee Beans',
        description: 'Premium roasted coffee beans',
        quantity: 8,
        lowStockThreshold: 10,
        expiryDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        expiryWarningDays: 14,
        category: 'Beverages',
        location: 'Shelf B2',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '3',
        barcode: '8410076472953',
        name: 'Extra Virgin Olive Oil',
        description: 'Cold-pressed Spanish olive oil',
        quantity: 15,
        lowStockThreshold: 5,
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        expiryWarningDays: 30,
        category: 'Condiments',
        location: 'Shelf C1',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '4',
        barcode: '3017620422003',
        name: 'Hazelnut Spread',
        description: 'Chocolate hazelnut spread',
        quantity: 3,
        lowStockThreshold: 10,
        expiryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // 3 days - expiring soon
        expiryWarningDays: 7,
        category: 'Spreads',
        location: 'Shelf A3',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '5',
        barcode: '5000159407236',
        name: 'Breakfast Cereal',
        description: 'Whole grain oat cereal',
        quantity: 45,
        lowStockThreshold: 15,
        expiryDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
        expiryWarningDays: 14,
        category: 'Breakfast',
        location: 'Shelf D1',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '6',
        barcode: '8076809513388',
        name: 'Spaghetti Pasta',
        description: 'Italian durum wheat pasta',
        quantity: 60,
        lowStockThreshold: 20,
        expiryDate: new Date(Date.now() + 730 * 24 * 60 * 60 * 1000),
        expiryWarningDays: 30,
        category: 'Pasta',
        location: 'Shelf E2',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '7',
        barcode: '7622210449283',
        name: 'Dark Chocolate Bar',
        description: '70% cocoa dark chocolate',
        quantity: 5,
        lowStockThreshold: 10,
        expiryDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // Expired 2 days ago
        expiryWarningDays: 7,
        category: 'Snacks',
        location: 'Shelf A1',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '8',
        barcode: '5449000000996',
        name: 'Sparkling Water',
        description: 'Natural mineral water',
        quantity: 120,
        lowStockThreshold: 30,
        expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        expiryWarningDays: 30,
        category: 'Beverages',
        location: 'Warehouse',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '9',
        barcode: '8718114710112',
        name: 'Greek Yogurt',
        description: 'Plain Greek-style yogurt',
        quantity: 18,
        lowStockThreshold: 10,
        expiryDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        expiryWarningDays: 5,
        category: 'Dairy',
        location: 'Cooler A',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '10',
        barcode: '5010477348678',
        name: 'Canned Tomatoes',
        description: 'Peeled Italian tomatoes',
        quantity: 35,
        lowStockThreshold: 15,
        expiryDate: new Date(Date.now() + 900 * 24 * 60 * 60 * 1000),
        expiryWarningDays: 60,
        category: 'Canned Goods',
        location: 'Shelf F1',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

export const alerts: InventoryAlert[] = [
    {
        id: "1",
        productId: "1",
        productName: "Organic Whole Milk",
        type: 'expiring_soon',
        message: "Organic whole milk expires in 4 days",
        severity: 'warning',
        createdAt: new Date(),
        acknowledged: true
    },
    {
        id: "2",
        productId: "2",
        productName: "Arabica Coffee Beans",
        type: 'expiring_soon',
        message: "Arabica Coffee Beans is low on stock (8 remaining)",
        severity: 'warning',
        createdAt: new Date(),
        acknowledged: true
    }
]

export const categories = () => {
    const categories = new Set(products.map(p => p.category))
    return Array.from(categories).sort();
} 
